FROM node:20-alpine

RUN apk add --no-cache openssl3 python3 py3-pip

RUN python3 -m venv /venv && /venv/bin/pip install pytest requests pytest-html

WORKDIR /app

ENV PATH="/venv/bin:$PATH"

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npx prisma generate --schema=./src/lib/schema.prisma

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Запускаем dev-сервер
CMD ["sh", "-c", "npx --yes prisma@5.22.0 db push --schema=./src/lib/schema.prisma --accept-data-loss --skip-generate && npm run dev"]