FROM node:20-alpine
RUN apk add --no-cache openssl
WORKDIR /app

# Копируем зависимости
COPY package.json package-lock.json ./
RUN npm install

# Копируем весь код
COPY . .

# Генерируем Prisma Client
RUN npx prisma generate --schema=./src/lib/schema.prisma

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Запускаем dev-сервер
CMD ["sh", "-c", "npx --yes prisma@5.22.0 db push --schema=./src/lib/schema.prisma --accept-data-loss --skip-generate && npm run dev"]